notation/urls.py
from django.conf.urls.defaults import patterns
from django.views.generic.list_detail import object_list
from django.contrib.auth.models import User
from cfai.notation.views import *
from cfai.notation.models import Entreprise, ProfilUtilisateur


liste_tuteurs_dict = {
    'queryset' : User.objects.filter(profilutilisateur__user_type='t').filter(profilutilisateur__suppression=None).order_by('last_name'),
    'template_name' : 'notation/tuteur_list.html'
    }

liste_formateurs_dict = {
    'queryset' : User.objects.filter(profilutilisateur__user_type__in=['f', 'F']).filter(profilutilisateur__suppression=None).order_by('last_name'),
    'template_name' : 'notation/formateur_list.html'
    }

liste_pilotes_dict = {
    'queryset' : User.objects.filter(profilutilisateur__user_type__in=['p', 'F']).filter(profilutilisateur__suppression=None).order_by('last_name'),
    'template_name' : 'notation/pilote_list.html'
    }

urlpatterns = patterns('',
    (r'^accounts/login/$',  'django.contrib.auth.views.login'),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page':'/'}),

    (r'^utilisateur/motdepasse/$', motdepasse),
    (r'^utilisateur/profil/$', profil),

    (r'^suppression/(?P<model>[a-zA-Z]+)/(?P<object_id>\d+)/$', suppression_objet),

    (r'^bulletins/$', liste_bulletin, None, 'liste_bulletin'),
    (r'^bulletins/(?P<blt_id>\d+)/$', bulletin, None, 'bulletin'),
    (r'^bulletins/(?P<blt_id>\d+)/annees/(?P<annee>\d+)/$', annee_bulletin),
    (r'^bulletins/(?P<blt_id>\d+)/annees/(?P<annee>\d+)/groupes/(?P<ens_id>\d+)/$', ensemble_bulletin),

    (r'^grilles/(?P<object_id>\d+)/annee/(?P<annee>\d+)/$', resume_grille, None, 'resume_grille'),

    (r'^entreprises/$', liste_entreprise, None, 'liste_entreprise'),
    (r'^entreprises/ajouter/$', detail_entreprise, None, 'ajouter_entreprise'),
    (r'^entreprises/(?P<object_id>\d+)/$', detail_entreprise, None, 'detail_entreprise'),

    (r'^eleves/$', liste_eleve, None, 'liste_eleve'),
    (r'^eleves/supprimes/$', liste_eleve_supprime, None, 'liste_eleve_supprime'),
    (r'^eleves/ajouter/$', ajouter_eleve, None, 'ajouter_eleve'),
    (r'^eleves/(?P<object_id>\d+)/$', modifier_eleve, None, 'detail_eleve'),

    (r'^tuteurs/$', object_list, liste_tuteurs_dict, 'liste_tuteur'),
    (r'^tuteurs/ajouter/$', ajouter_tuteur, None, 'ajouter_tuteur'),
    (r'^tuteurs/(?P<object_id>\d+)/$', detail_tuteur, None, 'detail_tuteur'),

    (r'^formateurs/$', object_list, liste_formateurs_dict, 'liste_formateur'),
    (r'^formateurs/ajouter/$', ajouter_formateur, None, 'ajouter_formateur'),
    (r'^formateurs/(?P<object_id>\d+)/$', detail_formateur, None, 'detail_formateur'),

    (r'^pilotes/$', object_list, liste_pilotes_dict, 'liste_pilote'),
    (r'^pilotes/ajouter/$', ajouter_pilote, None, 'ajouter_pilote'),
    (r'^pilotes/(?P<object_id>\d+)/$', detail_pilote, None, 'detail_pilote'),

    (r'^formations/$', liste_formation, None, 'liste_formation'),

    (r'^administratif/$', index_admin),
    (r'^gestion/$', index_gestion, None, 'index_gestion'),
    (r'^assistance/$', index_assistance, None, 'index_assistance'),
    (r'^formateur/$', index_formateur),
    (r'^tuteur/$', index_tuteur),
    (r'^eleve/$', index_eleve),
    (r'^recherche/$', recherche),
    (r'^$', index)
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from django.views.static import serve

admin.autodiscover()

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    (r'^', include('cfai.notation.urls')),
)

if settings.SERVE_STATIC == True:
    urlpatterns += patterns('',
       (r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
       (r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}))

notation/models.py
# -*- coding: utf-8 -*-

import os.path
import unicodedata

from datetime import date
from decimal import Decimal

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save
from django.contrib.auth.signals import user_logged_in
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.contrib import messages
from django.contrib.auth import logout
from django.utils.encoding import smart_unicode
from django.conf import settings

class Suppression(models.Model):
    """
    On utilise quelque chose comme
    file:///usr/share/doc/python-django-doc/html/ref/contrib/contenttypes.html#generic-relations
    pour avoir un lien vers l'objet supprimé et donc acceder facilement
    a ses attributes et methodes
    """
    createur = models.ForeignKey(User, editable=False)
    date_creation = models.DateField(u'Date de la suppression', auto_now_add=True)
    raison = models.TextField('Motif de la suppression')
    content_type = models.ForeignKey(ContentType, editable=False)
    object_id = models.PositiveIntegerField(editable=False)
    content_object = generic.GenericForeignKey('content_type', 'object_id')

    def __unicode__(self):
        return u'Suppression de %s par %s le %s' % (self.content_object, self.createur.get_full_name(), self.date_creation)

def supprimer_objet(obj, user, reason):
    obj.suppression = Suppression.objects.create(createur = user, raison = reason, content_object = obj)
    obj.save()

TYPES = (('e', u'Apprenti'),
         ('t', u'Tuteur entreprise'),
         ('f', u'Tuteur académique'),
         ('a', u'Administratif'),
         ('p', u'Pilotage'),
         ('F', u'Tuteur académique et Pilotage'))

APPRECIATIONS = (('v', u'Non renseigné'),
                 ('a', u'Acquis'),
                 ('n', u'Non acquis'),
                 ('e', u"En cours d'acquisition"),
                 ('p', u'Non applicable'))

APPRECIATIONS_UTBM = (('v', u'Non évalué'),
                      ('n', u'Notion'),
                      ('e', u'Application tutorée'),
                      ('a', u'Application autonome'),
                      ('m', u'Maîtrise'))

NOTES = ((1, '1'),
         (2, '2'),
         (3, '3'),
         (4, '4'),
         (5, '5'))

NOMS_ANNEES = [u'1ère année', u'2ème année', u'3ème année']

class ProfilUtilisateur(models.Model):
    user = models.OneToOneField(User, unique=True)
    user_type = models.CharField(u'Type', max_length=1, default='a', choices=TYPES)
    password_modified = models.BooleanField(default=False, editable=True)
    phone_number = models.CharField(u'N° de téléphone', max_length=15, blank=True)
    suppression = models.OneToOneField(Suppression, null=True, blank=True, editable=False)

    def __unicode__(self):
        return u'%s - %s' % (self.user.get_full_name(), self.get_user_type_display())

    def is_tuteur(self):
        return self.user_type == 't'
    def is_eleve(self):
        return self.user_type == 'e'
    def is_formateur(self):
        return self.user_type == 'f' or self.user_type == 'F'

    def is_administratif(self):
        return self.user_type == 'a'
    def is_pilote(self):
        return self.user_type == 'p' or self.user_type == 'F'
    def is_manitou(self):
        return self.is_administratif() or self.is_pilote()

    def _nom_complet(self):
        return '%s %s' % (self.user.last_name, self.user.first_name)
    nom_complet = property(_nom_complet)

    @models.permalink
    def get_absolute_url(self):
        if self.is_tuteur():
            return ('detail_tuteur', [self.id])
        if self.is_eleve():
            return ('detail_eleve', [self.id])
        if self.is_formateur():
            return ('detail_formateur', [self.id])
        if self.is_pilote():
            return ('detail_pilote', [self.id])
        return None


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profil, created = ProfilUtilisateur.objects.get_or_create(user=instance)
post_save.connect(create_user_profile, sender=User, dispatch_uid='create_user_profile')

def check_user(sender, request, user, **kwargs):
    profile = user.get_profile()
    if not profile.password_modified:
        messages.warning(request, u'Vous devez modifier votre mot de passe !')

    if profile.is_eleve():
        bulletins = Bulletin.objects.filter(eleve=user)
        if all(b.grille.archive for b in bulletins):
            messages.error(request, u"Vous n'avez plus accès au site")
            user.is_active = False
            user.save()
            logout(request)

user_logged_in.connect(check_user, sender=User, dispatch_uid='user_logged_in')


class Ecole(models.Model):
    class Meta:
        verbose_name = u'Ecole'
        verbose_name_plural = u'Ecoles'

    nom = models.CharField(max_length=100, blank=False)
    calcul_note = models.BooleanField(u'Calcul automatique des notes', default=False)
    poids_competences = models.PositiveIntegerField(u'Poids compétences', default=1, editable=True)
    poids_savoirs = models.PositiveIntegerField(u'Poids savoirs être', default=1, editable=True)
    logo = models.CharField(u'Nom du fichier logo', max_length=100, blank=False)
    date_creation = models.DateTimeField(u'Date création', auto_now_add=True)

    def __unicode__(self):
        return u'%s' % (self.nom)

    def appreciations(self):
        if self.id == 1:
            return APPRECIATIONS
        return APPRECIATIONS_UTBM

class Formation(models.Model):
    libelle = models.CharField(u'Libellé', max_length=80)
    # alter table notation_formation drop column duree;
    duree = models.PositiveIntegerField(u'Durée en années de la formation', editable=False, default=3)
    # Après création de l'ENSMM comme école d'id 1
    # alter table notation_formation add column ecole_id integer not null unique references "notation_ecole" ("id") default 1
    ecole = models.ForeignKey(Ecole, verbose_name='Ecole')

    def __unicode__(self):
        return self.libelle

class GrilleNotation(models.Model):
    """
    Une grille de notation existe pour une formation et une promotion.
    Chaque eleve est lie a une et une seule grille.
    """
    class Meta:
        verbose_name = u'Grille de notation'
        verbose_name_plural = u'Grilles de notation'
        ordering = ['frm', '-promotion']

    frm = models.ForeignKey(Formation, verbose_name='Formation')
    promotion = models.PositiveIntegerField(u'Première année de la promotion')
    duree = models.PositiveIntegerField(u'Durée en années de la formation')
    # Les poids ne sont plus utilisés et pourront être supprimés après filtrage des données
    poids_capacite = models.PositiveIntegerField(u'Poids de la moyenne des capacités dans la moyenne générale', default=1, editable=False)
    poids_savoir_etre = models.PositiveIntegerField(u'Poids de la moyenne des savoirs être dans la moyenne générale', default=1, editable=False)
    # alter table notation_grillenotation add column archive bool not null default false
    archive = models.BooleanField(u'Grille archivée (plus de modification)', default=False)

    def __unicode__(self):
        return u'%s / %d - %d' % (self.frm.libelle, self.promotion, self.promotion + self.duree)

    def annee_promotion_courante(self):
        """
        Retourne l'annee en cours de la promotion (0, 1, 2) pour la date
        du jour. Les années scolaires vont de septembre à août.

        Retourne -1 si la date est en dehors de la promotion.
        """
        ajd = date.today()
        for inc in range(0, self.duree):
            debut_annee = date(self.promotion + inc, 9, 1)
            fin_annee = date(self.promotion + inc + 1, 8, 30)
            if debut_annee <= ajd and ajd <= fin_annee:
                return inc
        return -1

    def nom_promotion_courante(self):
        annee = self.annee_promotion_courante()
        if annee == -1:
            return None
        return NOMS_ANNEES[annee]


class AutorisationVueGrille(models.Model):
    """
    Chaque enregistrement autorise à un utilisateur une vue
    en lecture seules à tous les bulletins d'une grille
    """
    grille = models.ForeignKey(GrilleNotation, verbose_name='Grille notation')
    utilisateur = models.ForeignKey(User, verbose_name='Utilisateur')

    def __unicode__(self):
        return u'%s - %s' % (self.grille, self.utilisateur)


class Entreprise(models.Model):
    class Meta:
        ordering = ['nom']

    nom = models.CharField(u'Nom', max_length=80)
    description = models.TextField(u'Adresse', blank=True)
    telephone = models.CharField(u'N° de téléphone', max_length=15, blank=True)
    fax = models.CharField(u'N° de fax', max_length=15, blank=True)

    def __unicode__(self):
        return self.nom

    @models.permalink
    def get_absolute_url(self):
        return ('detail_entreprise', [self.id])


class BulletinApprentiNonSupprime(models.Manager):
    def get_query_set(self):
        return super(BulletinApprentiNonSupprime, self).get_query_set().filter(eleve__profilutilisateur__suppression=None)
class BulletinApprentiSupprime(models.Manager):
    def get_query_set(self):
        return super(BulletinApprentiSupprime, self).get_query_set().exclude(eleve__profilutilisateur__suppression=None)
class BulletinApprenti(models.Manager):
    def get_query_set(self):
        return super(BulletinApprenti, self).get_query_set()

class Bulletin(models.Model):
    """
    Bulletin de notes d'un eleve pour une formation

    Il serait preferable point de vue structure et acces
    aux donnees de stocker un bulletin par annee. Cela
    permettrait d'acceder aux notes et aux moyennes tres
    facilement.
    """
    class Meta:
        verbose_name = u'Bulletin'
        verbose_name_plural = u'Bulletins'

    eleve = models.ForeignKey(User, related_name='eleve', verbose_name=u'Apprenti')

notation/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
<head>
    {% if user.is_authenticated %}
    <title>Notation des apprentis - {{ user.get_full_name }} - {{ user.get_profile.get_user_type_display }}</title>
    {% else %}
    <title>Notation des apprentis</title>
    {% endif %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="/static/css/base.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/print.css" media="print" />
</head>
<body>
    {% if messages %}
    <ul class="messagelist">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}

    <div id="navigation">
      {% if user.is_authenticated %}
      <b><a href="{% url notation.views.profil %}">{{ user.get_full_name }} ({{ user.get_profile.get_user_type_display }})</a></b> /
      <a href="{% url notation.views.motdepasse %}">modifier votre mot de passe</a> /
      <a href="{% url notation.views.index %}">page d'accueil</a> /
      <a href="{% url django.contrib.auth.views.logout %}">déconnexion</a>
      {% if user.get_profile.is_administratif %}
      <form id="recherche" action="" method="post">{% csrf_token %}
      <input type="text" maxlength="40" name="chaine" id="chaine"/>
      <input type="hidden" name="_search" value="Aller" />
      </form>
      {% endif %}
      {% endif %}
    </div>
    <div id="contenu">{% block content %}{% endblock %}</div>
    <div id="pied">
      v1.6.11
      propulsée par <a href="http://www.djangoproject.com/">django</a> |
      réalisée par <a href="http://www.octets.fr/">octets</a> |
      <a href="mailto:webmaster@formation-industries-fc.fr">contact</a>
      {% if user.is_staff %}
       | <a href="/admin/">administration</a>
      {% endif %}
    </div>

    <div id="entete">
      <div class="contenugauche">
	<a href="{% url notation.views.index %}"><img style="margin-left:5em" src="/static/images/{{ logo|default:"logo-itii.png"}}" style="vertical-align:top; margin-top:6px"/></a>
      </div>
      <div class="contenudroit">
	<a href="{% url notation.views.index %}"><img style="float:right; margin-right:5em" src="/static/images/logo-pole-formation.png" width="160" height="171"/></a>
      </div>
    </div>
</body>
</html>

notation/templates/index.html
{% extends "base.html" %}
{% block content %}
{% endblock %}

notation/templates/index_admin.html
{% extends "base.html" %}
{% block content %}

{% if user.get_profile.is_administratif %}
<h1>Menu administration</h1>
{% else %}
<h1>Menu pilotage</h1>
{% endif %}
<div class="actions">
  <div class="contenugauche">
    <a class="button" href="{% url index_gestion %}">Gestion</a>
    <p>Accès aux données administratives</p>
  </div>
  <div class="contenudroit">
    <a class="button" href="{% url index_assistance %}">Synthèse</a>
    <p>Accès aux tableau récapitulatifs et aux fiches de compétence des apprentis</p>
  </div>
</div>
{% endblock %}

notation/templates/index_assistance.html
{% extends "base.html" %}
{% block content %}

<h1>Synthèse</h1>
<div id="soustitre">
<a href="{% url notation.views.index_admin %}">retour à l'accueil</a>
</div>

{% for frm in formations %}
<h2>Formation {{ frm }}</h2>
{% for grille in frm.grillenotation_set.all %}
{% if grille.nom_promotion_courante  %}
<div class="actions" style="margin-left: 5%;">
<a class="button" href="{% url resume_grille grille.id grille.annee_promotion_courante %}">Apprentis {{ grille.nom_promotion_courante }}</a>
</div>
{% endif %}
{% endfor %}
{% endfor %}
{% endblock %}

notation/templates/index_eleve.html
{% extends "base.html" %}
{% block content %}

<h1>Mon bulletin</h1>
<ul>
  {% for blt in bulletins %}
  <li><a href="{% url notation.views.bulletin blt.id %}">{{ blt }}</a></li>
  {% endfor %}
</ul>
{% endblock %}

notation/templates/index_formateur.html
{% extends "base.html" %}
{% block content %}

<h1>Les bulletins de mes apprentis</h1>
<div class="table">
<ul>
  {% for blt in bulletins %}
  <li><a href="{% url notation.views.bulletin blt.id %}">{{ blt }}</a></li>
  {% endfor %}
</ul>

{% if enlecture.count %}
<h1>Les bulletins consultables</h1>
<ul>
  {% for blt in enlecture %}
  <li><a href="{% url notation.views.bulletin blt.id %}">{{ blt }}</a></li>
  {% endfor %}
</ul>
{% endif %}

</div>


<div class="actions">
{% if not user.get_profile.is_formateur %}
    <a class="button" href="{% url index_assistance %}">Synthèse</a>
{% endif %}
{% if user.get_profile.is_pilote %}
    <a class="button" href="{% url index_gestion %}">Gestion</a>
{% endif %}
</div>
{% endblock %}

notation/templates/index_gestion.html
{% extends "base.html" %}
{% block content %}

<h1>Gestion</h1>
<div id="soustitre">
<a href="{% url notation.views.index_admin %}">retour à l'accueil</a>
</div>

<div class="actions">
  <div class="contenugauche">
  <div><a class="button" href="{% url liste_entreprise %}">Les entreprises</a></div>
  <div><a class="button" href="{% url liste_eleve %}">Les apprentis</a></div>
  <div><a class="button" href="{% url liste_bulletin %}">Les bulletins de notes</a></div>
  <div><a class="button" href="{% url liste_formation %}">Les formations</a></div>
  </div>
  <div class="contenudroit">
  <div><a class="button" href="{% url liste_formateur %}">Les tuteurs académiques</a></div>
  <div><a class="button" href="{% url liste_tuteur %}">Les tuteurs entreprises</a></div>
  <div><a class="button" href="{% url liste_pilote %}">Les pilotes</a></div>
  </div>
</div>
{% endblock %}

notation/templates/index_tuteur.html
{% extends "base.html" %}
{% block content %}

<h1>Les bulletins à remplir</h1>
<ul>
{% for bulletin in bulletins %}
  <li><a href="{% url notation.views.bulletin bulletin.id %}">{{ bulletin.eleve.get_full_name }}</a></li>
{% endfor %}
</ul>
{% endblock %}

notation/templates/search.html
{% extends "base.html" %}
{% block content %}

<h1>Résultats de la recherche sur '{{ search_str }}'</h1>
{% if object_list %}
<ul>
{% for obj in object_list %}
  <li><a href="{{ obj.get_absolute_url }}">{{ obj }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>Aucun résultat</p>
{% endif %}
{% endblock %}