notation/urls.py
from django.conf.urls.defaults import patterns
from django.views.generic.list_detail import object_list
from django.contrib.auth.models import User
from cfai.notation.views import *
from cfai.notation.models import Entreprise, ProfilUtilisateur


liste_tuteurs_dict = {
    'queryset' : User.objects.filter(profilutilisateur__user_type='t').filter(profilutilisateur__suppression=None).order_by('last_name'),
    'template_name' : 'notation/tuteur_list.html'
    }

liste_formateurs_dict = {
    'queryset' : User.objects.filter(profilutilisateur__user_type__in=['f', 'F']).filter(profilutilisateur__suppression=None).order_by('last_name'),
    'template_name' : 'notation/formateur_list.html'
    }

liste_pilotes_dict = {
    'queryset' : User.objects.filter(profilutilisateur__user_type__in=['p', 'F']).filter(profilutilisateur__suppression=None).order_by('last_name'),
    'template_name' : 'notation/pilote_list.html'
    }

urlpatterns = patterns('',
    (r'^accounts/login/$',  'django.contrib.auth.views.login'),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page':'/'}),

    (r'^utilisateur/motdepasse/$', motdepasse),
    (r'^utilisateur/profil/$', profil),

    (r'^suppression/(?P<model>[a-zA-Z]+)/(?P<object_id>\d+)/$', suppression_objet),

    (r'^bulletins/$', liste_bulletin, None, 'liste_bulletin'),
    (r'^bulletins/(?P<blt_id>\d+)/$', bulletin, None, 'bulletin'),
    (r'^bulletins/(?P<blt_id>\d+)/annees/(?P<annee>\d+)/$', annee_bulletin),
    (r'^bulletins/(?P<blt_id>\d+)/annees/(?P<annee>\d+)/groupes/(?P<ens_id>\d+)/$', ensemble_bulletin),

    (r'^grilles/(?P<object_id>\d+)/annee/(?P<annee>\d+)/$', resume_grille, None, 'resume_grille'),

    (r'^entreprises/$', liste_entreprise, None, 'liste_entreprise'),
    (r'^entreprises/ajouter/$', detail_entreprise, None, 'ajouter_entreprise'),
    (r'^entreprises/(?P<object_id>\d+)/$', detail_entreprise, None, 'detail_entreprise'),

    (r'^eleves/$', liste_eleve, None, 'liste_eleve'),
    (r'^eleves/supprimes/$', liste_eleve_supprime, None, 'liste_eleve_supprime'),
    (r'^eleves/ajouter/$', ajouter_eleve, None, 'ajouter_eleve'),
    (r'^eleves/(?P<object_id>\d+)/$', modifier_eleve, None, 'detail_eleve'),

    (r'^tuteurs/$', object_list, liste_tuteurs_dict, 'liste_tuteur'),
    (r'^tuteurs/ajouter/$', ajouter_tuteur, None, 'ajouter_tuteur'),
    (r'^tuteurs/(?P<object_id>\d+)/$', detail_tuteur, None, 'detail_tuteur'),

    (r'^formateurs/$', object_list, liste_formateurs_dict, 'liste_formateur'),
    (r'^formateurs/ajouter/$', ajouter_formateur, None, 'ajouter_formateur'),
    (r'^formateurs/(?P<object_id>\d+)/$', detail_formateur, None, 'detail_formateur'),

    (r'^pilotes/$', object_list, liste_pilotes_dict, 'liste_pilote'),
    (r'^pilotes/ajouter/$', ajouter_pilote, None, 'ajouter_pilote'),
    (r'^pilotes/(?P<object_id>\d+)/$', detail_pilote, None, 'detail_pilote'),

    (r'^formations/$', liste_formation, None, 'liste_formation'),

    (r'^administratif/$', index_admin),
    (r'^gestion/$', index_gestion, None, 'index_gestion'),
    (r'^assistance/$', index_assistance, None, 'index_assistance'),
    (r'^formateur/$', index_formateur),
    (r'^tuteur/$', index_tuteur),
    (r'^eleve/$', index_eleve),
    (r'^recherche/$', recherche),
    (r'^$', index)
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from django.views.static import serve

admin.autodiscover()

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    (r'^', include('cfai.notation.urls')),
)

if settings.SERVE_STATIC == True:
    urlpatterns += patterns('',
       (r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
       (r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}))

notation/models.py
# -*- coding: utf-8 -*-

import os.path
import unicodedata

from datetime import date
from decimal import Decimal

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save
from django.contrib.auth.signals import user_logged_in
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.contrib import messages
from django.contrib.auth import logout
from django.utils.encoding import smart_unicode
from django.conf import settings

class Suppression(models.Model):
    """
    On utilise quelque chose comme
    file:///usr/share/doc/python-django-doc/html/ref/contrib/contenttypes.html#generic-relations
    pour avoir un lien vers l'objet supprimé et donc acceder facilement
    a ses attributes et methodes
    """
    createur = models.ForeignKey(User, editable=False)
    date_creation = models.DateField(u'Date de la suppression', auto_now_add=True)
    raison = models.TextField('Motif de la suppression')
    content_type = models.ForeignKey(ContentType, editable=False)
    object_id = models.PositiveIntegerField(editable=False)
    content_object = generic.GenericForeignKey('content_type', 'object_id')

    def __unicode__(self):
        return u'Suppression de %s par %s le %s' % (self.content_object, self.createur.get_full_name(), self.date_creation)

def supprimer_objet(obj, user, reason):
    obj.suppression = Suppression.objects.create(createur = user, raison = reason, content_object = obj)
    obj.save()

TYPES = (('e', u'Apprenti'),
         ('t', u'Tuteur entreprise'),
         ('f', u'Tuteur académique'),
         ('a', u'Administratif'),
         ('p', u'Pilotage'),
         ('F', u'Tuteur académique et Pilotage'))

APPRECIATIONS = (('v', u'Non renseigné'),
                 ('a', u'Acquis'),
                 ('n', u'Non acquis'),
                 ('e', u"En cours d'acquisition"),
                 ('p', u'Non applicable'))

APPRECIATIONS_UTBM = (('v', u'Non évalué'),
                      ('n', u'Notion'),
                      ('e', u'Application tutorée'),
                      ('a', u'Application autonome'),
                      ('m', u'Maîtrise'))

NOTES = ((1, '1'),
         (2, '2'),
         (3, '3'),
         (4, '4'),
         (5, '5'))

NOMS_ANNEES = [u'1ère année', u'2ème année', u'3ème année']

class ProfilUtilisateur(models.Model):
    user = models.OneToOneField(User, unique=True)
    user_type = models.CharField(u'Type', max_length=1, default='a', choices=TYPES)
    password_modified = models.BooleanField(default=False, editable=True)
    phone_number = models.CharField(u'N° de téléphone', max_length=15, blank=True)
    suppression = models.OneToOneField(Suppression, null=True, blank=True, editable=False)

    def __unicode__(self):
        return u'%s - %s' % (self.user.get_full_name(), self.get_user_type_display())

    def is_tuteur(self):
        return self.user_type == 't'
    def is_eleve(self):
        return self.user_type == 'e'
    def is_formateur(self):
        return self.user_type == 'f' or self.user_type == 'F'

    def is_administratif(self):
        return self.user_type == 'a'
    def is_pilote(self):
        return self.user_type == 'p' or self.user_type == 'F'
    def is_manitou(self):
        return self.is_administratif() or self.is_pilote()

    def _nom_complet(self):
        return '%s %s' % (self.user.last_name, self.user.first_name)
    nom_complet = property(_nom_complet)

    @models.permalink
    def get_absolute_url(self):
        if self.is_tuteur():
            return ('detail_tuteur', [self.id])
        if self.is_eleve():
            return ('detail_eleve', [self.id])
        if self.is_formateur():
            return ('detail_formateur', [self.id])
        if self.is_pilote():
            return ('detail_pilote', [self.id])
        return None


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profil, created = ProfilUtilisateur.objects.get_or_create(user=instance)
post_save.connect(create_user_profile, sender=User, dispatch_uid='create_user_profile')

def check_user(sender, request, user, **kwargs):
    profile = user.get_profile()
    if not profile.password_modified:
        messages.warning(request, u'Vous devez modifier votre mot de passe !')

    if profile.is_eleve():
        bulletins = Bulletin.objects.filter(eleve=user)
        if all(b.grille.archive for b in bulletins):
            messages.error(request, u"Vous n'avez plus accès au site")
            user.is_active = False
            user.save()
            logout(request)

user_logged_in.connect(check_user, sender=User, dispatch_uid='user_logged_in')


class Ecole(models.Model):
    class Meta:
        verbose_name = u'Ecole'
        verbose_name_plural = u'Ecoles'

    nom = models.CharField(max_length=100, blank=False)
    calcul_note = models.BooleanField(u'Calcul automatique des notes', default=False)
    poids_competences = models.PositiveIntegerField(u'Poids compétences', default=1, editable=True)
    poids_savoirs = models.PositiveIntegerField(u'Poids savoirs être', default=1, editable=True)
    logo = models.CharField(u'Nom du fichier logo', max_length=100, blank=False)
    date_creation = models.DateTimeField(u'Date création', auto_now_add=True)

    def __unicode__(self):
        return u'%s' % (self.nom)

    def appreciations(self):
        if self.id == 1:
            return APPRECIATIONS
        return APPRECIATIONS_UTBM

class Formation(models.Model):
    libelle = models.CharField(u'Libellé', max_length=80)
    # alter table notation_formation drop column duree;
    duree = models.PositiveIntegerField(u'Durée en années de la formation', editable=False, default=3)
    # Après création de l'ENSMM comme école d'id 1
    # alter table notation_formation add column ecole_id integer not null unique references "notation_ecole" ("id") default 1
    ecole = models.ForeignKey(Ecole, verbose_name='Ecole')

    def __unicode__(self):
        return self.libelle

class GrilleNotation(models.Model):
    """
    Une grille de notation existe pour une formation et une promotion.
    Chaque eleve est lie a une et une seule grille.
    """
    class Meta:
        verbose_name = u'Grille de notation'
        verbose_name_plural = u'Grilles de notation'
        ordering = ['frm', '-promotion']

    frm = models.ForeignKey(Formation, verbose_name='Formation')
    promotion = models.PositiveIntegerField(u'Première année de la promotion')
    duree = models.PositiveIntegerField(u'Durée en années de la formation')
    # Les poids ne sont plus utilisés et pourront être supprimés après filtrage des données
    poids_capacite = models.PositiveIntegerField(u'Poids de la moyenne des capacités dans la moyenne générale', default=1, editable=False)
    poids_savoir_etre = models.PositiveIntegerField(u'Poids de la moyenne des savoirs être dans la moyenne générale', default=1, editable=False)
    # alter table notation_grillenotation add column archive bool not null default false
    archive = models.BooleanField(u'Grille archivée (plus de modification)', default=False)

    def __unicode__(self):
        return u'%s / %d - %d' % (self.frm.libelle, self.promotion, self.promotion + self.duree)

    def annee_promotion_courante(self):
        """
        Retourne l'annee en cours de la promotion (0, 1, 2) pour la date
        du jour. Les années scolaires vont de septembre à août.

        Retourne -1 si la date est en dehors de la promotion.
        """
        ajd = date.today()
        for inc in range(0, self.duree):
            debut_annee = date(self.promotion + inc, 9, 1)
            fin_annee = date(self.promotion + inc + 1, 8, 30)
            if debut_annee <= ajd and ajd <= fin_annee:
                return inc
        return -1

    def nom_promotion_courante(self):
        annee = self.annee_promotion_courante()
        if annee == -1:
            return None
        return NOMS_ANNEES[annee]


class AutorisationVueGrille(models.Model):
    """
    Chaque enregistrement autorise à un utilisateur une vue
    en lecture seules à tous les bulletins d'une grille
    """
    grille = models.ForeignKey(GrilleNotation, verbose_name='Grille notation')
    utilisateur = models.ForeignKey(User, verbose_name='Utilisateur')

    def __unicode__(self):
        return u'%s - %s' % (self.grille, self.utilisateur)


class Entreprise(models.Model):
    class Meta:
        ordering = ['nom']

    nom = models.CharField(u'Nom', max_length=80)
    description = models.TextField(u'Adresse', blank=True)
    telephone = models.CharField(u'N° de téléphone', max_length=15, blank=True)
    fax = models.CharField(u'N° de fax', max_length=15, blank=True)

    def __unicode__(self):
        return self.nom

    @models.permalink
    def get_absolute_url(self):
        return ('detail_entreprise', [self.id])


class BulletinApprentiNonSupprime(models.Manager):
    def get_query_set(self):
        return super(BulletinApprentiNonSupprime, self).get_query_set().filter(eleve__profilutilisateur__suppression=None)
class BulletinApprentiSupprime(models.Manager):
    def get_query_set(self):
        return super(BulletinApprentiSupprime, self).get_query_set().exclude(eleve__profilutilisateur__suppression=None)
class BulletinApprenti(models.Manager):
    def get_query_set(self):
        return super(BulletinApprenti, self).get_query_set()

class Bulletin(models.Model):
    """
    Bulletin de notes d'un eleve pour une formation

    Il serait preferable point de vue structure et acces
    aux donnees de stocker un bulletin par annee. Cela
    permettrait d'acceder aux notes et aux moyennes tres
    facilement.
    """
    class Meta:
        verbose_name = u'Bulletin'
        verbose_name_plural = u'Bulletins'

    eleve = models.ForeignKey(User, related_name='eleve', verbose_name=u'Apprenti')

notation/templates/notation/annee_bulletin.html
{% extends "base.html" %}
{% block content %}

<h1>Bulletin de {{ bulletin.eleve.get_profile.nom_complet }} / Année {{ bulletin.grille.promotion|add:annee }} - {{ bulletin.grille.promotion|add:annee|add:1 }}
{% if bulletin.archive %}
 (archivé)
{% endif %}
</h1>
<div id="soustitre">
<a href="{% url notation.views.bulletin bulletin.id %}">choix de l'année</a>
</div>
<form action="" method="post">{% csrf_token %}
  <table>
    {% for field in thform %}
    <tr><th>
      {{ field.label_tag }}
      <ul>
	{% for ens in field.field.ensembles %}
	<li><a href="{% url notation.views.ensemble_bulletin bulletin.id annee ens.id %}">{{ ens }}</a></li>
	{% endfor %}
      </ul>
    </th><td>
      {% if field.errors %}
      <ul class="errorlist">
	{% for error in field.errors %}
	<li>{{ error|escape }}</li>
	{% endfor %}
      </ul>
      {% endif %}
      {{ field }}
      {% if field.help_text %}
      <br><span>{{ field.help_text|escape }}</span>
      {% endif %}
      <br><br>{{ field.field.prc }}% d'évaluations renseignées
    </td></tr>
    {% endfor %}

{% if not bulletin.archive or user.get_profile.is_administratif %}
{% if user.get_profile.is_tuteur or user.get_profile.is_administratif %}
{% if not calcul %}
  <tr><th></th><td>
    <input name="themes" type="submit" value="Enregistrer les notes compétences" />
  </td></tr>
{% endif %}
{% endif %}
{% endif %}
  </table>
</form>


<h1>Les savoirs être</h1>
<form action="" method="post">{% csrf_token %}
  <table>
  {{ form }}

{% if not bulletin.archive or user.get_profile.is_administratif %}
{% if user.get_profile.is_tuteur or user.get_profile.is_administratif %}
  <tr><th></th><td>
    <input type="submit" value="Enregistrer les notes savoir être" />
  </td></tr>
{% endif %}
{% endif %}
  </table>
</form>

<h1>Résultats à ce jour</h1>
  <table style="width:300px">
  <tr><th>Moyenne des compétences : </th><td>{{ moyenne.0.valeur_cp|floatformat:2 }}</td></tr>
  <tr><th>Moyenne savoir être : </th><td>{{ moyenne.0.valeur_sv|floatformat:2 }}</td></tr>
  <tr><th>Moyenne générale : </th><td>{{ moyenne.0.valeur_gn|floatformat:2 }}</td></tr>
  </table>
{% if bulletin.auteur_modification %}
  <p>Dernière modification du bulletin par {{ bulletin.auteur_modification.get_full_name }} le {{ bulletin.date_modification }}.</p>
{% endif %}
{% endblock %}

notation/templates/notation/bulletin.html
{% extends "base.html" %}
{% block content %}

<h1>{{ bulletin }}</h1>

{% if bulletin.archive %}
<h3>Ce bulletin est archivé.</h3>
{% endif %}

<p><a href="?format=xls">Fichier excel pour</a> le bulletin complet</p>
<ul>
  {% for annee in annees %}
  <li><a href="{% url notation.views.annee_bulletin bulletin.id annee %}">Année {{ bulletin.grille.promotion|add:annee }} - {{ bulletin.grille.promotion|add:annee|add:1 }}</a></li>
  {% endfor %}
</ul>
{% if bulletin.auteur_modification %}
  <p>Dernière modification par {{ bulletin.auteur_modification.get_full_name }} le {{ bulletin.date_modification }}.</p>
{% else %}
  <p>Aucune saisie n'a été faite sur ce bulletin</p>
{% endif %}
</br>

<h1>{{ bulletin.eleve.get_profile.nom_complet }}</h1>
<table>
    <tr><td><b>Adresse électronique</b></td><td><a href="mailto:{{ bulletin.eleve.email }}">{{ bulletin.eleve.email }}</a></td></tr>
    <tr><td><b>N° de téléphone</b></td><td>{{ bulletin.eleve.get_profile.phone_number }}</td></tr>
    <tr><td><b>Tuteur</b></td><td>{{ bulletin.tuteur.get_profile.nom_complet }} / <a href="mailto:{{ bulletin.tuteur.email }}">{{ bulletin.tuteur.email }}</a> / {{ bulletin.tuteur.get_profile.phone_number }}</td></tr>
    <tr><td><b>Tuteur académique</b></td><td>{{ bulletin.formateur.get_profile.nom_complet }} / <a href="mailto:{{ bulletin.formateur.email }}">{{ bulletin.formateur.email }}</a> / {{ bulletin.formateur.get_profile.phone_number }}</td></tr>
</table>
</br>

<h1>{{ bulletin.entreprise }}</h1>
<table>
    <tr><td><b>Adresse</b></td><td>{{ bulletin.entreprise.description }}</td></tr>
    <tr><td><b>N° de téléphone</b></td><td>{{ bulletin.entreprise.telephone }}</td></tr>
    <tr><td><b>N° de fax</b></td><td>{{ bulletin.entreprise.fax }}</td></tr>
</table>

<h1>Documents attachés</h1>
<h3>Liste des documents</h3>
{% if pjs %}
<ul>
{% for pj in pjs %}
<li>
- <a href="{{ pj.fichier.url }}">{{ pj.nom_fichier }}</a> ({{ pj.description }})
</li>
{% endfor %}
</ul>
{% else %}
<p>Aucun document pour l'instant</p>
{% endif %}


{% if user.get_profile.is_administratif %}
<br>
<h3>Ajout d'un document</h3>
<form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
  <table>
  {{ form }}
  <tr><th></th><td>
    <input name="valider" type="submit" value="Valider" />
  </td></tr>
  </table>
</form>
{% endif %}

{% endblock %}

notation/templates/notation/bulletin_list.html
{% extends "base.html" %}
{% block content %}
<h1>Les bulletins de {{ gr }}
{% if gr.archive %}
 (archivés)
{% endif %}
</h1>
<div class="table">
<ul>
{% for blt in object_list %}
  <li>
  <a href="{% url notation.views.bulletin blt.id %}">{{ blt }}</a>
   / <a href="{% url notation.views.bulletin blt.id %}?format=xls">Fichier excel</a>
  </li>
{% endfor %}
</ul>
</div>

<div class="filtre">
<h3>Filtrer par formation</h3>
<ul>
  {% for grille in grilles %}
  <li {% if grille = gr %}class="important"{% endif %}><a href="?id={{ grille.id }}">{{ grille }}</a></li>
  {% endfor %}
</ul>
</div>
{% endblock %}

notation/templates/notation/ensemble.html
{% extends "base.html" %}
{% block content %}

<h1>{{ ensemble }} / {{ bulletin.eleve.get_full_name }} ({{ bulletin.grille.promotion|add:annee }}-{{ bulletin.grille.promotion|add:annee|add:1 }})
{% if bulletin.archive %}
 (archivé)
{% endif %}
</h1>
<div id="soustitre">
<a href="{% url notation.views.annee_bulletin bulletin.id annee %}">retour à la liste</a>
{% if precedent %}
<a href="{% url notation.views.ensemble_bulletin bulletin.id annee precedent.id %}"> / précédent</a>
{% endif %}
{% if suivant %}
<a href="{% url notation.views.ensemble_bulletin bulletin.id annee suivant.id %}"> / suivant</a>
{% endif %}
</div>

  <form style="margin-left: 2%;" action="" method="post">{% csrf_token %}
    <table>
      {{ form }}

{% if not bulletin.archive or user.get_profile.is_administratif %}
{% if user.get_profile.is_administratif or user.get_profile.is_tuteur or user.get_profile.is_eleve %}
    <tr><th></th><td><input type="submit" value="Enregistrer et passer au groupe suivant" /></td></tr>
{% endif %}
{% endif %}
    </table>
  </form>
{% endblock %}

notation/templates/notation/entreprise_form.html
{% extends "base.html" %}
{% block content %}
{% if object %}
<h1>Détails de l'entreprise {{ object }}</h1>
{% else %}
<h1>Ajout d'une entreprise</h1>
{% endif %}
  <form style="margin-left: 10%;" action="" method="post">{% csrf_token %}
    <table>
    {{ form.as_table }}

    {% if user.get_profile.is_administratif %}
    <tr><th></th><td>
    {% if object %}
      <input type="submit" name="_save" value="Enregistrer et revenir à la liste" />
    {% else %}
      <input type="submit" name="_addanother" value="Enregistrer et saisir une autre entreprise" />
      <input type="submit" name="_save "value="Enregistrer et revenir à la liste" />
    {% endif %}
    </td></tr>
    {% endif %}
    
    </table>
  </form>

{% if object.bulletin_set.count %}
<h1>Les apprentis de l'entreprise</h1>
<ul>
{% for blt in object.bulletin_set.all %}
    <li><a href="{% url detail_eleve blt.eleve.id %}">{{ blt.eleve.get_profile.nom_complet }} ({{ blt.grille }})</a></li>
{% endfor %}
</ul>
{% endif %}
    
{% endblock %}

notation/templates/notation/entreprise_list.html
{% extends "base.html" %}
{% block content %}
<h1>Les entreprises</h1>

{% if user.get_profile.is_administratif %}
<div class="actions">
<a class="button" href="{% url ajouter_entreprise %}">Ajouter une entreprise</a>
</div>
{% endif %}

<table>
<thead><th>Nom</th><th>Adresse</th><th>Tél</th><th>Fax</th><th>Apprenti(s)</th></thead>
<tbody>
{% for etpr in object_list %}
<tr>
  <td><a href="{% url detail_entreprise etpr.id %}">{{ etpr.nom }}</a></td>
  <td>{{ etpr.description }}</td>
  <td>{{ etpr.telephone }}</td>
  <td>{{ etpr.fax }}</td>
  <td>
    {% for blt in etpr.bulletin_set.all %}
    <div><a href="{% url detail_eleve blt.eleve.id %}">{{ blt.eleve.get_profile.nom_complet }}</a></div>
    {% endfor %}
  <tr>
</tr>
{% endfor %}
</table>

{% endblock %}

notation/templates/notation/formateur_form.html
{% extends "base.html" %}
{% block content %}
{% if object %}
<h1>Détails du tuteur académique {{ object.get_full_name }}</h1>
{% else %}
<h1>Ajout d'un tuteur académique {{ object.get_full_name }}</h1>
{% endif %}
  <form style="margin-left: 10%;" action="" method="post">{% csrf_token %}
    <table>
    {{ form.as_table }}

{% if user.get_profile.is_administratif %}
    <tr><th></th><td>
{% if object %}
      <input type="submit" value="Enregistrer" />
      </td></tr><tr><th></th><td>
      <input type="submit" name="_reinit" value="Enregistrer et envoyer un email avec le mot de passe réinitialisé" />
      </td></tr><tr><th></th><td>
      <input type="submit" name="_delete" value="Supprimer ce tuteur académique des listes" />
{% else %}
      <input type="submit" name="_continuer" value="Enregistrer et saisir un autre tuteur académique" />
      <input type="submit" value="Enregistrer et revenir à la liste" />
{% endif %}
    </td></tr>
{% endif %}
    </table>
  </form>

{% if bulletins.count %}
<h1>Les bulletins de ce tuteur académique</h1>
<ul>
{% for blt in bulletins %}
    <li><a href="{% url detail_eleve blt.eleve.id %}">{{ blt.eleve.get_profile.nom_complet }} ({{ blt.grille }})</a></li>
{% endfor %}
</ul>
{% endif %}

<h1>Les autorisations de ce tuteur académique</h1>

  <form style="margin-left: 10%;" action="" method="post">{% csrf_token %}
    <table>
    {{ autoform.as_table }}
{% if user.get_profile.is_administratif %}
    <tr><th></th><td>
{% if object %}
      <input type="submit" name="_saveauto" value="Enregistrer" />
{% endif %}
    </td></tr>
{% endif %}
    </table>
  </form>

{% endblock %}

notation/templates/notation/formateur_list.html
{% extends "base.html" %}
{% block content %}
<h1>Les tuteurs académiques</h1>

{% if user.get_profile.is_administratif %}
<div class="actions">
<a class="button" href="{% url notation.views.ajouter_formateur %}">Ajouter un tuteur académique</a>
</div>
{% endif %}

<ul>
{% for obj in object_list %}
  <li><a href="{% url detail_formateur obj.id %}">{{ obj.get_profile.nom_complet }}</a></li>
{% endfor %}
</ul>
{% endblock %}

notation/templates/notation/motdepasse.html
{% extends "base.html" %}
{% block content %}

<h1>Modification du mot de passe</h1>

<form action="" method="POST">{% csrf_token %}
<table>
{{ password_form }}
<tr><td></td><td><input type="submit" value="Enregistrer" /></td></tr>
</table>
</form>

{% endblock %}

notation/templates/notation/pilote_form.html
{% extends "base.html" %}
{% block content %}
{% if object %}
<h1>Détails du pilote {{ object.get_full_name }}</h1>
{% else %}
<h1>Ajout d'un pilote {{ object.get_full_name }}</h1>
{% endif %}
  <form style="margin-left: 10%;" action="" method="post">{% csrf_token %}
    <table>
    {{ form.as_table }}
    <tr><th></th><td>
{% if object %}
      <input type="submit" value="Enregistrer" />
      </td></tr><tr><th></th><td>
      <input type="submit" name="_reinit" value="Enregistrer et envoyer un email avec le mot de passe réinitialisé" />
      </td></tr><tr><th></th><td>
      <input type="submit" name="_delete" value="Supprimer ce pilote des listes" />
{% else %}
      <input type="submit" name="_continuer" value="Enregistrer et saisir un autre pilote" />
      <input type="submit" value="Enregistrer et revenir à la liste" />
{% endif %}
    </td></tr>
    </table>
  </form>

{% endblock %}